// <auto-generated />
using System;
using Bagatka.AiSloth.Secrets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Secrets.Data.Migrations;

[DbContext(typeof(SecretsDbContext))]
partial class SecretsDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261008091525_Initial";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("secrets")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Secrets.Model.Secret", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("name");

                b.Property<byte[]>("SealedValue")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("sealed_value");

                b.Property<DateTimeOffset>("SetAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("set_at");

                b.Property<Guid>("SetBy")
                    .HasColumnType("uuid")
                    .HasColumnName("set_by");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_secrets");

                b.HasIndex("WorkspaceId", "Name")
                    .IsUnique()
                    .HasDatabaseName("ix_secrets_workspace_id_name");

                b.ToTable("secrets", "secrets");
            });
#pragma warning restore 612, 618
    }
}
