using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Bagatka.AiSloth.Cli;

// Source-generated, as Native AOT requires.
[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, WriteIndented = true)]
[JsonSerializable(typeof(MachineCredential))]
[JsonSerializable(typeof(HostsFile))]
[JsonSerializable(typeof(UpdateCheck))]
[JsonSerializable(typeof(Wire.HostDiscovery))]
[JsonSerializable(typeof(Wire.CodeSignIn))]
[JsonSerializable(typeof(Wire.TokenExchange))]
[JsonSerializable(typeof(Wire.SignedIn))]
[JsonSerializable(typeof(Wire.LinkCode))]
[JsonSerializable(typeof(Wire.WorkspacePage))]
[JsonSerializable(typeof(Wire.CreateInvite))]
[JsonSerializable(typeof(Wire.Invite))]
[JsonSerializable(typeof(Wire.AcceptInvite))]
[JsonSerializable(typeof(Wire.Resource))]
[JsonSerializable(typeof(IReadOnlyList<Wire.AccountKind>))]
[JsonSerializable(typeof(IReadOnlyList<Wire.Account>))]
[JsonSerializable(typeof(Wire.Account))]
[JsonSerializable(typeof(Wire.AddAccount))]
[JsonSerializable(typeof(Wire.StartAccountSignIn))]
[JsonSerializable(typeof(Wire.AccountSignInStarted))]
[JsonSerializable(typeof(Wire.CompleteAccountSignIn))]
[JsonSerializable(typeof(IReadOnlyList<Wire.Harness>))]
[JsonSerializable(typeof(IReadOnlyList<Wire.Provider>))]
[JsonSerializable(typeof(IReadOnlyList<Wire.Secret>))]
[JsonSerializable(typeof(Wire.Secret))]
[JsonSerializable(typeof(Wire.SetSecret))]
[JsonSerializable(typeof(Wire.Chat))]
[JsonSerializable(typeof(Wire.ChatPage))]
[JsonSerializable(typeof(Wire.CheckpointPage))]
[JsonSerializable(typeof(IReadOnlyList<Wire.HarnessState>))]
[JsonSerializable(typeof(Wire.Instructions))]
[JsonSerializable(typeof(Wire.SetInstructions))]
[JsonSerializable(typeof(Wire.StartChat))]
[JsonSerializable(typeof(Wire.SendMessage))]
[JsonSerializable(typeof(Wire.SentMessage))]
[JsonSerializable(typeof(Wire.ChatEvent))]
[JsonSerializable(typeof(Wire.NookSetup))]
[JsonSerializable(typeof(Wire.ProcessOutput))]
[JsonSerializable(typeof(Wire.ProcessExit))]
[JsonSerializable(typeof(IReadOnlyList<Wire.Person>))]
[JsonSerializable(typeof(Wire.Problem))]
[JsonSerializable(typeof(Wire.Nook))]
[JsonSerializable(typeof(Wire.NookPage))]
[JsonSerializable(typeof(Wire.GitHubConnectionStarted))]
[JsonSerializable(typeof(Wire.GitHubConnectionProgress))]
[JsonSerializable(typeof(Wire.GitHubAccount))]
[JsonSerializable(typeof(Wire.AvailableRepositories))]
[JsonSerializable(typeof(IReadOnlyList<Wire.Repository>))]
[JsonSerializable(typeof(Wire.Repository))]
[JsonSerializable(typeof(Wire.AddRepository))]
[JsonSerializable(typeof(Wire.GitSettings))]
[JsonSerializable(typeof(Wire.SetGitSettings))]
[JsonSerializable(typeof(Wire.Push))]
[JsonSerializable(typeof(IReadOnlyList<Wire.PushedSource>))]
internal sealed partial class CliJsonContext : JsonSerializerContext;
