// <auto-generated />
using System;
using Bagatka.AiSloth.Workspaces.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Workspaces.Data.Migrations;

[DbContext(typeof(WorkspacesDbContext))]
[Migration("20261004200028_Initial")]
partial class _20261004200028_Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("workspaces")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.Grant", b =>
            {
                b.Property<Guid>("ResourceId")
                    .HasColumnType("uuid")
                    .HasColumnName("resource_id");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<string>("Access")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("access");

                b.Property<string>("ResourceKind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("resource_kind");

                b.HasKey("ResourceId", "UserId")
                    .HasName("pk_grants");

                b.HasIndex("UserId", "ResourceId")
                    .HasDatabaseName("ix_grants_user_id_resource_id");

                b.ToTable("grants", "workspaces");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.ResourceLink", b =>
            {
                b.Property<Guid>("ChildId")
                    .HasColumnType("uuid")
                    .HasColumnName("child_id");

                b.Property<Guid>("ParentId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_id");

                b.Property<string>("ChildKind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("child_kind");

                b.Property<string>("ParentKind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("parent_kind");

                b.HasKey("ChildId", "ParentId")
                    .HasName("pk_links");

                b.ToTable("links", "workspaces");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.StoredInvite", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset?>("AcceptedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("accepted_at");

                b.Property<Guid?>("AcceptedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("accepted_by");

                b.Property<string>("Access")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("access");

                b.Property<byte[]>("CodeHash")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("code_hash");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<Guid>("ResourceId")
                    .HasColumnType("uuid")
                    .HasColumnName("resource_id");

                b.Property<string>("ResourceKind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("resource_kind");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("Id")
                    .HasName("pk_invites");

                b.HasIndex("CodeHash")
                    .IsUnique()
                    .HasDatabaseName("ix_invites_code_hash");

                b.ToTable("invites", "workspaces");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.Workspace", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.HasKey("Id")
                    .HasName("pk_workspaces");

                b.ToTable("workspaces", "workspaces");
            });
#pragma warning restore 612, 618
    }
}
