// <auto-generated />
using System;
using Bagatka.AiSloth.Workspaces.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Workspaces.Data.Migrations;

[DbContext(typeof(WorkspacesDbContext))]
partial class WorkspacesDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261004105401_Initial";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("workspaces")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.Member", b =>
            {
                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("role");

                b.HasKey("WorkspaceId", "UserId")
                    .HasName("pk_members");

                b.HasIndex("UserId", "WorkspaceId")
                    .HasDatabaseName("ix_members_user_id_workspace_id");

                b.ToTable("members", "workspaces");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.Workspace", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.HasKey("Id")
                    .HasName("pk_workspaces");

                b.ToTable("workspaces", "workspaces");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.Member", b =>
            {
                b.HasOne("Bagatka.AiSloth.Workspaces.Model.Workspace", null)
                    .WithMany("Members")
                    .HasForeignKey("WorkspaceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_members_workspaces_workspace_id");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Workspaces.Model.Workspace", b =>
            {
                b.Navigation("Members");
            });
#pragma warning restore 612, 618
    }
}
