// <auto-generated />
using System;
using Bagatka.AiSloth.Sources.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Sources.Data.Migrations;

[DbContext(typeof(SourcesDbContext))]
[Migration("20261005125207_Initial")]
partial class _20261005125207_Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("sources")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Sources.Model.GitHubConnection", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<DateTimeOffset?>("AccessExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("access_expires_at");

                b.Property<DateTimeOffset>("ConnectedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("connected_at");

                b.Property<long>("GitHubUserId")
                    .HasColumnType("bigint")
                    .HasColumnName("git_hub_user_id");

                b.Property<string>("Login")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("login");

                b.Property<string>("Name")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("name");

                b.Property<DateTimeOffset?>("RefreshExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("refresh_expires_at");

                b.Property<byte[]>("SealedAccessToken")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("sealed_access_token");

                b.Property<byte[]>("SealedRefreshToken")
                    .HasColumnType("bytea")
                    .HasColumnName("sealed_refresh_token");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("UserId")
                    .HasName("pk_github_connections");

                b.ToTable("github_connections", "sources");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Sources.Model.GitHubConnectionAttempt", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<TimeSpan>("Interval")
                    .HasColumnType("interval")
                    .HasColumnName("interval");

                b.Property<DateTimeOffset>("NextPollAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("next_poll_at");

                b.Property<byte[]>("SealedDeviceCode")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("sealed_device_code");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_github_connection_attempts");

                b.HasIndex("UserId", "ExpiresAt")
                    .HasDatabaseName("ix_github_connection_attempts_user_id_expires_at");

                b.ToTable("github_connection_attempts", "sources");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Sources.Model.PersonGitSettings", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid")
                    .HasColumnName("user_id");

                b.Property<bool>("AiSlothCoAuthor")
                    .HasColumnType("boolean")
                    .HasColumnName("ai_sloth_co_author");

                b.Property<string>("AuthorEmail")
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)")
                    .HasColumnName("author_email");

                b.Property<string>("AuthorName")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("author_name");

                b.Property<string>("BranchPrefix")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("branch_prefix");

                b.Property<string>("CommitterEmail")
                    .HasMaxLength(254)
                    .HasColumnType("character varying(254)")
                    .HasColumnName("committer_email");

                b.Property<string>("CommitterName")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("committer_name");

                b.HasKey("UserId")
                    .HasName("pk_git_settings");

                b.ToTable("git_settings", "sources");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Sources.Model.Repository", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("AddedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("added_at");

                b.Property<Guid>("AddedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("added_by");

                b.Property<string>("DefaultBranch")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("default_branch");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.Property<string>("Owner")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("owner");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("url");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_repositories");

                b.HasIndex("WorkspaceId", "Name")
                    .IsUnique()
                    .HasDatabaseName("ix_repositories_workspace_id_name");

                b.ToTable("repositories", "sources");
            });
#pragma warning restore 612, 618
    }
}
