// <auto-generated />
using System;
using Bagatka.AiSloth.AgentAccounts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.AgentAccounts.Data.Migrations;

[DbContext(typeof(AgentAccountsDbContext))]
[Migration("20261004163154_Initial")]
partial class _20261004163154_Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("agent_accounts")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.AgentAccounts.Model.AgentAccount", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("AddedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("added_at");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("kind");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("name");

                b.Property<Guid?>("OwnerId")
                    .HasColumnType("uuid")
                    .HasColumnName("owner_id");

                b.Property<byte[]>("SealedSecret")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("sealed_secret");

                b.Property<Guid?>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_accounts");

                b.HasIndex("OwnerId", "Id")
                    .HasDatabaseName("ix_accounts_owner_id_id");

                b.HasIndex("WorkspaceId", "Id")
                    .HasDatabaseName("ix_accounts_workspace_id_id");

                b.ToTable("accounts", "agent_accounts", t =>
                    {
                        t.HasCheckConstraint("ck_accounts_one_owner", "(workspace_id IS NULL) <> (owner_id IS NULL)");
                    });
            });
#pragma warning restore 612, 618
    }
}
