// <auto-generated />
using System;
using Bagatka.AiSloth.Machines.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Machines.Data.Migrations;

[DbContext(typeof(MachinesDbContext))]
[Migration("20261004135117_Initial")]
partial class _20261004135117_Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("machines")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Machines.Model.Machine", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("AddedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("added_at");

                b.Property<DateTimeOffset?>("CodeExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("code_expires_at");

                b.Property<byte[]>("CodeHash")
                    .HasColumnType("bytea")
                    .HasColumnName("code_hash");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("name");

                b.Property<byte[]>("TokenHash")
                    .HasColumnType("bytea")
                    .HasColumnName("token_hash");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_machines");

                b.HasIndex("CodeHash")
                    .IsUnique()
                    .HasDatabaseName("ix_machines_code_hash");

                b.HasIndex("WorkspaceId", "Id")
                    .HasDatabaseName("ix_machines_workspace_id_id");

                b.ToTable("machines", "machines");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Machines.Model.Placement", b =>
            {
                b.Property<Guid>("Key")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("key");

                b.Property<Guid>("MachineId")
                    .HasColumnType("uuid")
                    .HasColumnName("machine_id");

                b.HasKey("Key")
                    .HasName("pk_placements");

                b.HasIndex("MachineId")
                    .HasDatabaseName("ix_placements_machine_id");

                b.ToTable("placements", "machines");
            });
#pragma warning restore 612, 618
    }
}
