<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Bagatka.AiSloth.Secrets.Contracts\Bagatka.AiSloth.Secrets.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Foundation\Bagatka.Foundation.Modules\Bagatka.Foundation.Modules.csproj" />
  </ItemGroup>

</Project>
