// <auto-generated />
using System;
using System.Collections.Generic;
using Bagatka.AiSloth.Nooks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Nooks.Data.Migrations;

[DbContext(typeof(NooksDbContext))]
[Migration("20261004164339_AddNookHarness")]
partial class _20261004164339_AddNookHarness
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("nooks")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.Nook", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<byte[]>("DaemonTokenHash")
                    .HasColumnType("bytea")
                    .HasColumnName("daemon_token_hash");

                b.Property<long?>("DiskAvailableBytes")
                    .HasColumnType("bigint")
                    .HasColumnName("disk_available_bytes");

                b.Property<long?>("DiskTotalBytes")
                    .HasColumnType("bigint")
                    .HasColumnName("disk_total_bytes");

                b.Property<string>("Harness")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("harness");

                b.Property<string>("Location")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("location");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("character varying(40)")
                    .HasColumnName("provider");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_nooks");

                b.HasIndex("Status", "Id")
                    .HasDatabaseName("ix_nooks_status_id");

                b.HasIndex("WorkspaceId", "Id")
                    .HasDatabaseName("ix_nooks_workspace_id_id");

                b.ToTable("nooks", "nooks");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.Process", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.PrimitiveCollection<List<string>>("Arguments")
                    .IsRequired()
                    .HasColumnType("text[]")
                    .HasColumnName("arguments");

                b.Property<string>("Command")
                    .IsRequired()
                    .HasMaxLength(4096)
                    .HasColumnType("character varying(4096)")
                    .HasColumnName("command");

                b.Property<int?>("ExitCode")
                    .HasColumnType("integer")
                    .HasColumnName("exit_code");

                b.Property<Guid>("NookId")
                    .HasColumnType("uuid")
                    .HasColumnName("nook_id");

                b.Property<string>("Retention")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("retention");

                b.Property<DateTimeOffset>("StartedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("started_at");

                b.Property<string>("WorkingDirectory")
                    .HasMaxLength(4096)
                    .HasColumnType("character varying(4096)")
                    .HasColumnName("working_directory");

                b.HasKey("Id")
                    .HasName("pk_processes");

                b.HasIndex("NookId", "Id")
                    .HasDatabaseName("ix_processes_nook_id_id");

                b.ToTable("processes", "nooks");
            });
#pragma warning restore 612, 618
    }
}
