// <auto-generated />
using System;
using System.Collections.Generic;
using Bagatka.AiSloth.Nooks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Nooks.Data.Migrations;

[DbContext(typeof(NooksDbContext))]
partial class NooksDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261005140239_Checkpoints";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("nooks")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.Checkpoint", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid>("NookId")
                    .HasColumnType("uuid")
                    .HasColumnName("nook_id");

                b.Property<string>("Note")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("note");

                b.Property<int>("Number")
                    .HasColumnType("integer")
                    .HasColumnName("number");

                b.HasKey("Id")
                    .HasName("pk_checkpoints");

                b.HasIndex("NookId", "Id")
                    .HasDatabaseName("ix_checkpoints_nook_id_id");

                b.HasIndex("NookId", "Number")
                    .IsUnique()
                    .HasDatabaseName("ix_checkpoints_nook_id_number");

                b.ToTable("checkpoints", "nooks");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.CheckpointPart", b =>
            {
                b.Property<Guid>("CheckpointId")
                    .HasColumnType("uuid")
                    .HasColumnName("checkpoint_id");

                b.Property<string>("Path")
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("path");

                b.Property<string>("Commit")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("commit");

                b.Property<string>("ObjectKey")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("object_key");

                b.Property<string>("Previous")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("previous");

                b.HasKey("CheckpointId", "Path")
                    .HasName("pk_checkpoint_parts");

                b.ToTable("checkpoint_parts", "nooks");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.Nook", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int?>("CopyCheckpoint")
                    .HasColumnType("integer")
                    .HasColumnName("copy_checkpoint");

                b.Property<Guid?>("CopyOf")
                    .HasColumnType("uuid")
                    .HasColumnName("copy_of");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("created_by");

                b.Property<byte[]>("DaemonTokenHash")
                    .HasColumnType("bytea")
                    .HasColumnName("daemon_token_hash");

                b.Property<long?>("DiskAvailableBytes")
                    .HasColumnType("bigint")
                    .HasColumnName("disk_available_bytes");

                b.Property<long?>("DiskTotalBytes")
                    .HasColumnType("bigint")
                    .HasColumnName("disk_total_bytes");

                b.Property<string>("Harness")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("harness");

                b.PrimitiveCollection<List<string>>("KeptPaths")
                    .IsRequired()
                    .HasColumnType("text[]")
                    .HasColumnName("kept_paths");

                b.Property<string>("Location")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("location");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("character varying(40)")
                    .HasColumnName("provider");

                b.Property<bool>("SourcesReady")
                    .HasColumnType("boolean")
                    .HasColumnName("sources_ready");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_nooks");

                b.HasIndex("Status", "Id")
                    .HasDatabaseName("ix_nooks_status_id");

                b.HasIndex("WorkspaceId", "Id")
                    .HasDatabaseName("ix_nooks_workspace_id_id");

                b.ToTable("nooks", "nooks");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.Process", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.PrimitiveCollection<List<string>>("Arguments")
                    .IsRequired()
                    .HasColumnType("text[]")
                    .HasColumnName("arguments");

                b.Property<string>("Command")
                    .IsRequired()
                    .HasMaxLength(4096)
                    .HasColumnType("character varying(4096)")
                    .HasColumnName("command");

                b.Property<int?>("ExitCode")
                    .HasColumnType("integer")
                    .HasColumnName("exit_code");

                b.Property<Guid>("NookId")
                    .HasColumnType("uuid")
                    .HasColumnName("nook_id");

                b.Property<string>("Retention")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("retention");

                b.Property<DateTimeOffset>("StartedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("started_at");

                b.Property<string>("WorkingDirectory")
                    .HasMaxLength(4096)
                    .HasColumnType("character varying(4096)")
                    .HasColumnName("working_directory");

                b.HasKey("Id")
                    .HasName("pk_processes");

                b.HasIndex("NookId", "Id")
                    .HasDatabaseName("ix_processes_nook_id_id");

                b.ToTable("processes", "nooks");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.SourceCopy", b =>
            {
                b.Property<Guid>("NookId")
                    .HasColumnType("uuid")
                    .HasColumnName("nook_id");

                b.Property<string>("Name")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.Property<string>("Branch")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("branch");

                b.Property<string>("Commit")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("commit");

                b.Property<Guid>("RepositoryId")
                    .HasColumnType("uuid")
                    .HasColumnName("repository_id");

                b.HasKey("NookId", "Name")
                    .HasName("pk_source_copies");

                b.ToTable("source_copies", "nooks");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Nooks.Model.CheckpointPart", b =>
            {
                b.HasOne("Bagatka.AiSloth.Nooks.Model.Checkpoint", null)
                    .WithMany()
                    .HasForeignKey("CheckpointId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_checkpoint_parts_checkpoints_checkpoint_id");
            });
#pragma warning restore 612, 618
    }
}
