// <auto-generated />
using System;
using Bagatka.Foundation.Modules.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.Foundation.Modules.Data.Migrations;

[DbContext(typeof(InstanceLeaseDbContext))]
partial class InstanceLeaseDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261006172455_InstanceLease";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("hosting")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.Foundation.Modules.Data.InstanceLease", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<Guid?>("Holder")
                    .HasColumnType("uuid")
                    .HasColumnName("holder");

                b.HasKey("Id")
                    .HasName("pk_instance_lease");

                b.ToTable("instance_lease", "hosting");

                b.HasData(
                    new
                    {
                        Id = 1,
                        ExpiresAt = new DateTimeOffset(new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                    });
            });
#pragma warning restore 612, 618
    }
}
