<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Foundation\Bagatka.Foundation\Bagatka.Foundation.csproj" />
    <ProjectReference Include="..\..\Sources\Bagatka.AiSloth.Sources.Contracts\Bagatka.AiSloth.Sources.Contracts.csproj" />
    <ProjectReference Include="..\..\Workspaces\Bagatka.AiSloth.Workspaces.Contracts\Bagatka.AiSloth.Workspaces.Contracts.csproj" />
  </ItemGroup>

</Project>
