// <auto-generated />
using System;
using Bagatka.AiSloth.Chats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Chats.Data.Migrations;

[DbContext(typeof(ChatsDbContext))]
[Migration("20261004152155_Initial")]
partial class _20261004152155_Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("chats")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.Chat", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid?>("HarnessProcessId")
                    .HasColumnType("uuid")
                    .HasColumnName("harness_process_id");

                b.Property<byte[]>("HarnessTokenHash")
                    .HasColumnType("bytea")
                    .HasColumnName("harness_token_hash");

                b.Property<long>("LastSequence")
                    .HasColumnType("bigint")
                    .HasColumnName("last_sequence");

                b.Property<Guid>("NookId")
                    .HasColumnType("uuid")
                    .HasColumnName("nook_id");

                b.Property<long>("OutputOffset")
                    .HasColumnType("bigint")
                    .HasColumnName("output_offset");

                b.Property<string>("SessionId")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("session_id");

                b.Property<DateTimeOffset>("StartedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("started_at");

                b.Property<Guid>("StartedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("started_by");

                b.Property<bool>("SupportsSteering")
                    .HasColumnType("boolean")
                    .HasColumnName("supports_steering");

                b.Property<Guid?>("TurnMessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("turn_message_id");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_chats");

                b.HasIndex("HarnessTokenHash")
                    .IsUnique()
                    .HasDatabaseName("ix_chats_harness_token_hash");

                b.HasIndex("NookId", "Id")
                    .HasDatabaseName("ix_chats_nook_id_id");

                b.ToTable("chats", "chats");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.Message", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ChatId")
                    .HasColumnType("uuid")
                    .HasColumnName("chat_id");

                b.Property<DateTimeOffset>("SentAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("sent_at");

                b.Property<Guid>("SentBy")
                    .HasColumnType("uuid")
                    .HasColumnName("sent_by");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("state");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(100000)
                    .HasColumnType("character varying(100000)")
                    .HasColumnName("text");

                b.HasKey("Id")
                    .HasName("pk_messages");

                b.HasIndex("ChatId", "State", "Id")
                    .HasDatabaseName("ix_messages_chat_id_state_id");

                b.ToTable("messages", "chats");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.StoredEvent", b =>
            {
                b.Property<Guid>("ChatId")
                    .HasColumnType("uuid")
                    .HasColumnName("chat_id");

                b.Property<long>("Sequence")
                    .HasColumnType("bigint")
                    .HasColumnName("sequence");

                b.Property<DateTimeOffset>("At")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("at");

                b.Property<string>("Data")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("data");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("kind");

                b.HasKey("ChatId", "Sequence")
                    .HasName("pk_events");

                b.ToTable("events", "chats");
            });
#pragma warning restore 612, 618
    }
}
