// <auto-generated />
using System;
using Bagatka.AiSloth.Chats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagatka.AiSloth.Chats.Data.Migrations;

[DbContext(typeof(ChatsDbContext))]
partial class ChatsDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261005153006_CheckpointsStateAndInstructions";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("chats")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.Chat", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid?>("AccountOwnerId")
                    .HasColumnType("uuid")
                    .HasColumnName("account_owner_id");

                b.Property<Guid>("AgentAccountId")
                    .HasColumnType("uuid")
                    .HasColumnName("agent_account_id");

                b.Property<Guid?>("CheckpointAfter")
                    .HasColumnType("uuid")
                    .HasColumnName("checkpoint_after");

                b.Property<string>("Harness")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("harness");

                b.Property<Guid?>("HarnessProcessId")
                    .HasColumnType("uuid")
                    .HasColumnName("harness_process_id");

                b.Property<string>("HarnessStateFiles")
                    .HasMaxLength(366000)
                    .HasColumnType("character varying(366000)")
                    .HasColumnName("harness_state_files");

                b.Property<byte[]>("HarnessTokenHash")
                    .HasColumnType("bytea")
                    .HasColumnName("harness_token_hash");

                b.Property<long>("LastSequence")
                    .HasColumnType("bigint")
                    .HasColumnName("last_sequence");

                b.Property<bool>("LoadingSession")
                    .HasColumnType("boolean")
                    .HasColumnName("loading_session");

                b.Property<Guid>("NookId")
                    .HasColumnType("uuid")
                    .HasColumnName("nook_id");

                b.Property<long>("OutputOffset")
                    .HasColumnType("bigint")
                    .HasColumnName("output_offset");

                b.Property<string>("ResumableSessionId")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("resumable_session_id");

                b.Property<string>("SessionId")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("session_id");

                b.Property<DateTimeOffset>("StartedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("started_at");

                b.Property<Guid>("StartedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("started_by");

                b.Property<bool>("SupportsSteering")
                    .HasColumnType("boolean")
                    .HasColumnName("supports_steering");

                b.Property<Guid?>("TurnMessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("turn_message_id");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.HasKey("Id")
                    .HasName("pk_chats");

                b.HasIndex("HarnessTokenHash")
                    .IsUnique()
                    .HasDatabaseName("ix_chats_harness_token_hash");

                b.HasIndex("NookId")
                    .IsUnique()
                    .HasDatabaseName("ix_chats_nook_id");

                b.HasIndex("WorkspaceId", "Id")
                    .HasDatabaseName("ix_chats_workspace_id_id");

                b.ToTable("chats", "chats");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.HarnessState", b =>
            {
                b.Property<Guid>("PersonId")
                    .HasColumnType("uuid")
                    .HasColumnName("person_id");

                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.Property<string>("Harness")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("harness");

                b.Property<long>("Bytes")
                    .HasColumnType("bigint")
                    .HasColumnName("bytes");

                b.Property<DateTimeOffset>("SavedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("saved_at");

                b.Property<Guid>("SavedFrom")
                    .HasColumnType("uuid")
                    .HasColumnName("saved_from");

                b.Property<byte[]>("Sha256")
                    .IsRequired()
                    .HasColumnType("bytea")
                    .HasColumnName("sha256");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("PersonId", "WorkspaceId", "Harness")
                    .HasName("pk_harness_states");

                b.ToTable("harness_states", "chats");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.Message", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ChatId")
                    .HasColumnType("uuid")
                    .HasColumnName("chat_id");

                b.Property<bool>("IsProposal")
                    .HasColumnType("boolean")
                    .HasColumnName("is_proposal");

                b.Property<Guid?>("ProposalId")
                    .HasColumnType("uuid")
                    .HasColumnName("proposal_id");

                b.Property<DateTimeOffset>("SentAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("sent_at");

                b.Property<Guid>("SentBy")
                    .HasColumnType("uuid")
                    .HasColumnName("sent_by");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("state");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(100000)
                    .HasColumnType("character varying(100000)")
                    .HasColumnName("text");

                b.HasKey("Id")
                    .HasName("pk_messages");

                b.HasIndex("ChatId", "State", "Id")
                    .HasDatabaseName("ix_messages_chat_id_state_id");

                b.ToTable("messages", "chats");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.PersonalInstructions", b =>
            {
                b.Property<Guid>("PersonId")
                    .HasColumnType("uuid")
                    .HasColumnName("person_id");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(10000)
                    .HasColumnType("character varying(10000)")
                    .HasColumnName("text");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("PersonId")
                    .HasName("pk_personal_instructions");

                b.ToTable("personal_instructions", "chats");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.StoredEvent", b =>
            {
                b.Property<Guid>("ChatId")
                    .HasColumnType("uuid")
                    .HasColumnName("chat_id");

                b.Property<long>("Sequence")
                    .HasColumnType("bigint")
                    .HasColumnName("sequence");

                b.Property<DateTimeOffset>("At")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("at");

                b.Property<string>("Data")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("data");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("kind");

                b.HasKey("ChatId", "Sequence")
                    .HasName("pk_events");

                b.ToTable("events", "chats");
            });

        modelBuilder.Entity("Bagatka.AiSloth.Chats.Model.WorkspaceInstructions", b =>
            {
                b.Property<Guid>("WorkspaceId")
                    .HasColumnType("uuid")
                    .HasColumnName("workspace_id");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(10000)
                    .HasColumnType("character varying(10000)")
                    .HasColumnName("text");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<Guid>("UpdatedBy")
                    .HasColumnType("uuid")
                    .HasColumnName("updated_by");

                b.HasKey("WorkspaceId")
                    .HasName("pk_workspace_instructions");

                b.ToTable("workspace_instructions", "chats");
            });
#pragma warning restore 612, 618
    }
}
