<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Bagatka.AiSloth.Workspaces.Contracts\Bagatka.AiSloth.Workspaces.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\Foundation\Bagatka.Foundation.Modules\Bagatka.Foundation.Modules.csproj" />
  </ItemGroup>

</Project>
