<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Foundation\Bagatka.Foundation\Bagatka.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Foundation\Bagatka.Foundation.Modules\Bagatka.Foundation.Modules.csproj" />
    <ProjectReference Include="..\..\src\Aspire\Bagatka.ServiceDefaults\Bagatka.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\src\ControlPlane\Bagatka.AiSloth.WebApi\Bagatka.AiSloth.WebApi.csproj" />
    <ProjectReference Include="..\..\src\ControlPlane\Modules\Nooks\Bagatka.AiSloth.Nooks.Contracts\Bagatka.AiSloth.Nooks.Contracts.csproj" />
    <ProjectReference Include="..\..\src\ControlPlane\Modules\Workspaces\Bagatka.AiSloth.Workspaces.Contracts\Bagatka.AiSloth.Workspaces.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Daemon\Bagatka.AiSloth.Daemon\Bagatka.AiSloth.Daemon.csproj" />
    <ProjectReference Include="..\..\src\Daemon\Bagatka.AiSloth.DaemonProtocol\Bagatka.AiSloth.DaemonProtocol.csproj" />
    <ProjectReference Include="..\..\src\Sandboxing\Bagatka.Sandboxing\Bagatka.Sandboxing.csproj" />
    <ProjectReference Include="..\..\src\Sandboxing\Bagatka.Sandboxing.Docker\Bagatka.Sandboxing.Docker.csproj" />
    <ProjectReference Include="..\..\src\Sdk\Bagatka.Sdk.Docker\Bagatka.Sdk.Docker.csproj" />
  </ItemGroup>

</Project>
